version: '3.9'

services:
  server:
    container_name: server
    build:
      context: ./
      dockerfile: Dockerfile.dev
    ports:
      - '4040:4040'
    volumes:
      - ./:/app
      - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend

  redis-server:
    image: redis/redis-stack:latest
    ports:
      - '6379:6379'
      - '8001:8001'
    restart: 'unless-stopped'

networks:
  backend:
    driver: bridge

volumes:
  data:
    driver: local
